"""
main.py
-------
Week 5 Assignment: Backend API Server

Endpoints:
  POST   /command                 -> kick off the agent, returns {task_id}
  GET    /status/{task_id}        -> current progress/result of that task
  GET    /user/profile            -> read stored user memory
  POST   /user/profile            -> write/update stored user memory
  WS     /ws/{task_id}            -> live step-by-step updates while agent runs
  GET    /docs                    -> Swagger UI (auto-generated by FastAPI)
"""

import uuid
import traceback
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware

from app import database as db
from app.models import CommandRequest, CommandResponse, TaskStatusResponse, UserProfile
from app.agent_bridge import run_agent, shutdown_agent
from app.websocket_manager import manager

app = FastAPI(
    title="AI Browser Agent — Backend API",
    description="Week 5: FastAPI server connecting the frontend to the Week 4 LangChain browser agent.",
    version="1.0.0",
)

# Allow the Cloudflare Pages frontend (and local dev) to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten this to your actual frontend origin(s) in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
async def on_startup():
    await db.init_db()


@app.on_event("shutdown")
async def on_shutdown():
    # Cleanly closes the Playwright browser launched by the Week 4 agent.
    await shutdown_agent()


# --------------------------------------------------------------------------
# /command
# --------------------------------------------------------------------------

async def _execute_task(task_id: str, command: str):
    """Runs in the background: drives the agent and persists + broadcasts
    every step as it happens."""
    await db.update_task_status(task_id, status="running")
    await manager.broadcast(task_id, {"type": "status", "status": "running"})

    async def on_step(step: dict):
        await db.append_task_step(task_id, step)
        await manager.broadcast(task_id, {"type": "step", **step})

    try:
        result = await run_agent(command, on_step)
        await db.update_task_status(task_id, status="completed", result=result)
        await manager.broadcast(task_id, {"type": "status", "status": "completed", "result": result})
    except Exception as exc:  # keep the server alive even if the agent throws
        # Print the FULL traceback to the terminal so we can actually see
        # what broke (str(exc) alone can be empty for some exception types).
        print(f"\n[task {task_id}] FAILED:")
        traceback.print_exc()

        error_message = f"{type(exc).__name__}: {exc}" if str(exc) else type(exc).__name__
        await db.update_task_status(task_id, status="failed", error=error_message)
        await manager.broadcast(task_id, {"type": "status", "status": "failed", "error": error_message})


@app.post("/command", response_model=CommandResponse, tags=["agent"])
async def post_command(payload: CommandRequest, background_tasks: BackgroundTasks):
    """Accepts a natural-language command, starts the agent as a background
    task, and immediately returns a task_id you can poll or subscribe to."""
    if not payload.command.strip():
        raise HTTPException(status_code=400, detail="command must not be empty")

    task_id = str(uuid.uuid4())
    await db.create_task(task_id, payload.command)
    background_tasks.add_task(_execute_task, task_id, payload.command)
    return CommandResponse(task_id=task_id, status="queued")


# --------------------------------------------------------------------------
# /status/{task_id}
# --------------------------------------------------------------------------

@app.get("/status/{task_id}", response_model=TaskStatusResponse, tags=["agent"])
async def get_status(task_id: str):
    task = await db.get_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="task_id not found")
    return task


# --------------------------------------------------------------------------
# /user/profile
# --------------------------------------------------------------------------

@app.get("/user/profile", tags=["user"])
async def get_user_profile():
    profile = await db.get_profile()
    if not profile:
        return {}
    return profile


@app.post("/user/profile", tags=["user"])
async def set_user_profile(profile: UserProfile):
    updated = await db.upsert_profile(
        name=profile.name,
        email=profile.email,
        phone=profile.phone,
        address=profile.address,
        resume_text=profile.resume_text,
    )
    return updated


# --------------------------------------------------------------------------
# WebSocket: /ws/{task_id}
# --------------------------------------------------------------------------

@app.websocket("/ws/{task_id}")
async def websocket_status(websocket: WebSocket, task_id: str):
    await manager.connect(task_id, websocket)
    try:
        # Replay history so far (in case the client connects mid-task)
        task = await db.get_task(task_id)
        if task:
            await websocket.send_json({"type": "history", "task": task})

        # Then just keep the connection open; broadcasts from _execute_task
        # push new messages. We still read incoming messages (e.g. pings)
        # so the connection doesn't get dropped by some proxies.
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(task_id, websocket)


@app.get("/", tags=["meta"])
async def root():
    return {
        "message": "AI Browser Agent backend is running.",
        "docs": "/docs",
        "endpoints": ["POST /command", "GET /status/{task_id}", "GET/POST /user/profile", "WS /ws/{task_id}"],
    }
